// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class tbClientes
    {
        public tbClientes()
        {
            tbClientePorVehiculo = new HashSet<tbClientePorVehiculo>();
            tbVehiculos = new HashSet<tbVehiculos>();
            tbVentas = new HashSet<tbVentas>();
        }

        public int clie_ID { get; set; }
        public int vehi_ID { get; set; }
        public string clie_Nombres { get; set; }
        public string clie_Apellidos { get; set; }
        public string clie_Sexo { get; set; }
        public DateTime clie_FechaNacimiento { get; set; }
        public string clie_Telefono { get; set; }
        public string clie_CorreoElectronico { get; set; }
        public string muni_ID { get; set; }
        public DateTime? clie_FechaCreacion { get; set; }
        public int? clie_UserCreacion { get; set; }
        public DateTime? clie_FechaModificacion { get; set; }
        public int? clie_UserModificacion { get; set; }
        public bool? clie_Estado { get; set; }

        public virtual tbUsuarios clie_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios clie_UserModificacionNavigation { get; set; }
        public virtual tbMunicipios muni { get; set; }
        public virtual tbVehiculos vehi { get; set; }
        public virtual ICollection<tbClientePorVehiculo> tbClientePorVehiculo { get; set; }
        public virtual ICollection<tbVehiculos> tbVehiculos { get; set; }
        public virtual ICollection<tbVentas> tbVentas { get; set; }
    }
}