// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class tbClientePorVehiculo
    {
        public int clvh_ID { get; set; }
        public int clie_ID { get; set; }
        public int vehi_ID { get; set; }
        public bool? clvh_Estado { get; set; }
        public int clvh_UserCreacion { get; set; }
        public DateTime? clvh_FechaCreacion { get; set; }
        public int? clvh_UserModificacion { get; set; }
        public DateTime? clvh_FechaModificacion { get; set; }

        public virtual tbClientes clie { get; set; }
        public virtual tbUsuarios clvh_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios clvh_UserModificacionNavigation { get; set; }
        public virtual tbVehiculos vehi { get; set; }
    }
}