// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class tbDetallesCompras
    {
        public int deco_ID { get; set; }
        public int comp_ID { get; set; }
        public int resp_ID { get; set; }
        public int deco_Cantidad { get; set; }
        public decimal deco_Preciocompra { get; set; }
        public decimal? deco_MontoTotal { get; set; }
        public bool? deco_Estado { get; set; }
        public int deco_UserCreacion { get; set; }
        public DateTime? deco_FechaCreacion { get; set; }
        public int? deco_UserModificacion { get; set; }
        public DateTime? deco_FechaModificacion { get; set; }

        public virtual tbCompras comp { get; set; }
        public virtual tbUsuarios deco_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios deco_UserModificacionNavigation { get; set; }
        public virtual tbRepuestos resp { get; set; }
    }
}