// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int estacivi_ID { get; set; }
        public string estacivi_Nombre { get; set; }
        public int estacivi_UserCreacion { get; set; }
        public DateTime estacivi_FechaCreacion { get; set; }
        public int? estacivi_UserModificacion { get; set; }
        public DateTime? estacivi_FechaModificacion { get; set; }
        public bool? estacivi_Estado { get; set; }

        public virtual tbUsuarios estacivi_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios estacivi_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}