// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class tbMarcas
    {
        public tbMarcas()
        {
            tbModelos = new HashSet<tbModelos>();
            tbRepuestos = new HashSet<tbRepuestos>();
        }

        public int marc_ID { get; set; }
        public string marc_Nombre { get; set; }
        public DateTime? marc_FechaCreacion { get; set; }
        public int? marc_UserCreacion { get; set; }
        public DateTime? marc_FechaModificacion { get; set; }
        public int? marc_UserModificacion { get; set; }
        public bool? marc_Estado { get; set; }

        public virtual tbUsuarios marc_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios marc_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbModelos> tbModelos { get; set; }
        public virtual ICollection<tbRepuestos> tbRepuestos { get; set; }
    }
}