// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class tbModelos
    {
        public tbModelos()
        {
            tbVehiculos = new HashSet<tbVehiculos>();
        }

        public int mode_ID { get; set; }
        public int marc_ID { get; set; }
        public string mode_Nombre { get; set; }
        public DateTime? mode_FechaCreacion { get; set; }
        public int? mode_UserCreacion { get; set; }
        public DateTime? mode_FechaModificacion { get; set; }
        public int? mode_UserModificacion { get; set; }
        public bool? mode_Estado { get; set; }

        public virtual tbMarcas marc { get; set; }
        public virtual tbUsuarios mode_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios mode_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbVehiculos> tbVehiculos { get; set; }
    }
}