// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbClientes = new HashSet<tbClientes>();
            tbEmpleados = new HashSet<tbEmpleados>();
            tbSucursales = new HashSet<tbSucursales>();
        }

        public string muni_ID { get; set; }
        public string muni_Nombre { get; set; }
        public string depa_ID { get; set; }
        public int muni_UserCreacion { get; set; }
        public DateTime muni_FechaCreacion { get; set; }
        public int? muni_UserModificacion { get; set; }
        public DateTime? muni_FechaModificacion { get; set; }
        public bool? muni_Estado { get; set; }

        public virtual tbDepartamentos depa { get; set; }
        public virtual tbUsuarios muni_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios muni_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientes { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbSucursales> tbSucursales { get; set; }
    }
}