// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class tbRepuestos
    {
        public tbRepuestos()
        {
            tbDetallesCompras = new HashSet<tbDetallesCompras>();
            tbDetallesventas = new HashSet<tbDetallesventas>();
        }

        public int resp_ID { get; set; }
        public string resp_Descripcion { get; set; }
        public decimal resp_Precio { get; set; }
        public int prov_ID { get; set; }
        public int marc_ID { get; set; }
        public string resp_Anio { get; set; }
        public DateTime? resp_FechaCreacion { get; set; }
        public int? resp_UserCreacion { get; set; }
        public DateTime? resp_FechaModificacion { get; set; }
        public int? resp_UserModificacion { get; set; }
        public bool? resp_Estado { get; set; }

        public virtual tbMarcas marc { get; set; }
        public virtual tbProveedores prov { get; set; }
        public virtual tbUsuarios resp_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios resp_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbDetallesCompras> tbDetallesCompras { get; set; }
        public virtual ICollection<tbDetallesventas> tbDetallesventas { get; set; }
    }
}