// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class tbServicios
    {
        public tbServicios()
        {
            tbDetallesventas = new HashSet<tbDetallesventas>();
        }

        public int serv_ID { get; set; }
        public string serv_Descripcion { get; set; }
        public DateTime? serv_FechaCreacion { get; set; }
        public int? serv_UserCreacion { get; set; }
        public DateTime? serv_FechaModificacion { get; set; }
        public int? serv_UserModificacion { get; set; }
        public bool? serv_Estado { get; set; }

        public virtual tbUsuarios serv_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios serv_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbDetallesventas> tbDetallesventas { get; set; }
    }
}