// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class tbSucursales
    {
        public tbSucursales()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
            tbVentas = new HashSet<tbVentas>();
        }

        public int sucu_ID { get; set; }
        public string sucu_Descripcion { get; set; }
        public string muni_ID { get; set; }
        public string sucu_DireccionExacta { get; set; }
        public DateTime sucu_FechaCreacion { get; set; }
        public int sucu_UserCreacion { get; set; }
        public DateTime? sucu_FechaModificacion { get; set; }
        public int? sucu_UserModificacion { get; set; }
        public bool? sucu_Estado { get; set; }

        public virtual tbMunicipios muni { get; set; }
        public virtual tbUsuarios sucu_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios sucu_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
        public virtual ICollection<tbVentas> tbVentas { get; set; }
    }
}