// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class tbVentas
    {
        public tbVentas()
        {
            tbDetallesventas = new HashSet<tbDetallesventas>();
        }

        public int vent_Id { get; set; }
        public DateTime vent_Fecha { get; set; }
        public int clie_ID { get; set; }
        public decimal? vent_Descuento { get; set; }
        public decimal? vent_MontoFinal { get; set; }
        public int sucu_ID { get; set; }
        public int vent_UserCreacion { get; set; }
        public DateTime? vent_FechaCreacion { get; set; }
        public int? vent_UserModificacion { get; set; }
        public DateTime? vent_FechaModificacion { get; set; }
        public int? meto_ID { get; set; }
        public int? vehi_ID { get; set; }

        public virtual tbClientes clie { get; set; }
        public virtual tbMetodosPago meto { get; set; }
        public virtual tbSucursales sucu { get; set; }
        public virtual tbVehiculos vehi { get; set; }
        public virtual tbUsuarios vent_UserCreacionNavigation { get; set; }
        public virtual tbUsuarios vent_UserModificacionNavigation { get; set; }
        public virtual ICollection<tbDetallesventas> tbDetallesventas { get; set; }
    }
}