// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class VW_Modelos
    {
        public int mode_ID { get; set; }
        public int marc_ID { get; set; }
        public string marc_Nombre { get; set; }
        public string mode_Nombre { get; set; }
        public DateTime? mode_FechaCreacion { get; set; }
        public int? mode_UserCreacion { get; set; }
        public string mode_UserCreacion_Nombre { get; set; }
        public DateTime? mode_FechaModificacion { get; set; }
        public int? mode_UserModificacion { get; set; }
        public string mode_UserModificaciones_Nombre { get; set; }
        public bool mode_Estado { get; set; }
    }
}