// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class VW_RepuestosMasVendidos2
    {
        public string resp_Descripcion { get; set; }
        public int? CantidadRepuestos { get; set; }
    }
}