// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class VW_ServiciosMasSolicitados
    {
        public string serv_Descripcion { get; set; }
        public int? CantidadServicios { get; set; }
    }
}