// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class VW_tbRoles
    {
        public int role_ID { get; set; }
        public string role_Nombre { get; set; }
        public int role_UserCreacion { get; set; }
        public string role_UserCreacion_Nombre { get; set; }
        public DateTime role_FechaCreacion { get; set; }
        public int? role_UserModificacion { get; set; }
        public string role_UserModificacion_Nombre { get; set; }
        public DateTime? role_FechaModificacion { get; set; }
        public bool role_Estado { get; set; }
    }
}