// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class VW_tbUsuarios
    {
        public int user_ID { get; set; }
        public string user_NombreUsuario { get; set; }
        public string user_Contrasena { get; set; }
        public bool? user_EsAdmin { get; set; }
        public int? role_ID { get; set; }
        public int? empe_ID { get; set; }
        public int? user_UserCreacion { get; set; }
        public string user_UserCreacion_Nombre { get; set; }
        public DateTime user_FechaCreacion { get; set; }
        public int? user_UserModificacion { get; set; }
        public string user_UserModificacion_Nombre { get; set; }
        public DateTime? user_FechaModificacion { get; set; }
        public bool user_Estado { get; set; }
    }
}