// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class VW_tbMarcas
    {
        public int marc_ID { get; set; }
        public string marc_Nombre { get; set; }
        public DateTime? marc_FechaCreacion { get; set; }
        public int? marc_UserCreacion { get; set; }
        public string marc_UserCreacion_Nombre { get; set; }
        public DateTime? marc_FechaModificacion { get; set; }
        public int? marc_UserModificacion { get; set; }
        public string marc_UserModificacion_Nombre { get; set; }
        public bool marc_Estado { get; set; }
    }
}