// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class VW_tbVehiculos
    {
        public int vehi_ID { get; set; }
        public int mode_ID { get; set; }
        public string mode_Nombre { get; set; }
        public string Modelo_Matricula { get; set; }
        public string vehi_Matricula { get; set; }
        public string vehi_anio { get; set; }
        public DateTime? vehi_FechaCreacion { get; set; }
        public int? vehi_UserCreacion { get; set; }
        public string vehi_UserCreacion_Nombre { get; set; }
        public DateTime? vehi_FechaModificacion { get; set; }
        public int? vehi_UserModificacion { get; set; }
        public string vehi_UserModificacion_Nombre { get; set; }
        public bool vehi_Estado { get; set; }
    }
}