// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class VW_tbRepuestos
    {
        public int resp_ID { get; set; }
        public string resp_Descripcion { get; set; }
        public decimal resp_Precio { get; set; }
        public int prov_ID { get; set; }
        public string prov_Nombre { get; set; }
        public int marc_ID { get; set; }
        public string marc_Nombre { get; set; }
        public string resp_Anio { get; set; }
        public DateTime? resp_FechaCreacion { get; set; }
        public int? resp_UserCreacion { get; set; }
        public string resp_UserCreacion_Nombre { get; set; }
        public DateTime? resp_FechaModificacion { get; set; }
        public int? resp_UserModificacion { get; set; }
        public string resp_UserModificacion_Nombre { get; set; }
        public bool resp_Estado { get; set; }
    }
}