// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class VW_tbServicios
    {
        public int serv_ID { get; set; }
        public string serv_Descripcion { get; set; }
        public decimal? serv_Precio { get; set; }
        public DateTime? serv_FechaCreacion { get; set; }
        public int? serv_UserCreacion { get; set; }
        public string serv_UserCreacion_Nombre { get; set; }
        public DateTime? serv_FechaModificacion { get; set; }
        public int? serv_UserModificacion { get; set; }
        public string serv_UserModificacion_Nombre { get; set; }
        public bool serv_Estado { get; set; }
    }
}