// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class VW_tbEstadosCiviles
    {
        public int estacivi_ID { get; set; }
        public string estacivi_Nombre { get; set; }
        public int estacivi_UserCreacion { get; set; }
        public string estacivi_UserCreacion_Nombre { get; set; }
        public DateTime estacivi_FechaCreacion { get; set; }
        public int? estacivi_UserModificacion { get; set; }
        public string estacivi_UserModificacion_Nombre { get; set; }
        public DateTime? estacivi_FechaModificacion { get; set; }
        public bool estacivi_Estado { get; set; }
    }
}