// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class VW_tbVentas
    {
        public int vent_Id { get; set; }
        public DateTime vent_Fecha { get; set; }
        public int clie_ID { get; set; }
        public string clie_Nombres { get; set; }
        public int? vehi_ID { get; set; }
        public string vehi_Matricula { get; set; }
        public int? meto_ID { get; set; }
        public string meto_Nombre { get; set; }
        public decimal? vent_Descuento { get; set; }
        public decimal? vent_MontoFinal { get; set; }
        public int sucu_ID { get; set; }
        public string sucu_Descripcion { get; set; }
        public int vent_UserCreacion { get; set; }
        public string vent_UserCreacion_Nombre { get; set; }
        public DateTime? vent_FechaCreacion { get; set; }
        public int? vent_UserModificacion { get; set; }
        public string vent_UserModificacion_Nombre { get; set; }
        public DateTime? vent_FechaModificacion { get; set; }
    }
}