// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class vwClientesConMasVehiculos
    {
        public int clie_ID { get; set; }
        public string clie_Nombres { get; set; }
        public int? total_vehiculos { get; set; }
    }
}