// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Taller.Entities.Entities
{
    public partial class vwTopProveedores
    {
        public string prov_Nombre { get; set; }
        public int? TotalRepuestos { get; set; }
    }
}